import React, { Suspense } from "react";
import type { Metadata } from "next";
import "@styles/scss/main.scss";
import HeaderView from "@widgets/Header";
import FooterView from "@widgets/Footer";
import PreLoader from "@components/PreLoader";

export const metadata: Metadata = {
  title: "TEDˣCCET",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <Suspense fallback={<PreLoader/>}>
          <div className="relative">
            <HeaderView />
            {children}
            <FooterView />
          </div>
        </Suspense>
      </body>
    </html>
  );
}
